# Generated by Django 5.2.6 on 2025-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeoftransport',
            name='mode_name',
            field=models.CharField(choices=[('tricycle', 'Tricycle'), ('tuktuk', 'Tuktuk'), ('bus', 'Bus'), ('jeepney', 'Jeepney'), ('train', 'Train'), ('motorcycle', 'Motorcycle')], max_length=20),
        ),
    ]
