# Generated by Django 5.2.6 on 2025-10-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_modeoftransport_mode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='api.terminal'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='modeoftransport',
            unique_together={('mode_name', 'fare_type')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('terminal', 'destination', 'mode')},
        ),
    ]
