# Generated by Django 5.2.6 on 2025-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_route_destination_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='route',
            name='destination_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
    ]
