# Generated by Django 5.2.6 on 2025-10-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_destination_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='terminal',
            unique_together={('latitude', 'longitude')},
        ),
    ]
