# Generated by Django 5.2.6 on 2025-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_route_created_at_route_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('complete', 'Complete Data Export'), ('terminals', 'Terminals Only'), ('routes', 'Routes and Stops'), ('regions', 'Regions and Cities')], help_text='Type of cached export', max_length=20, unique=True)),
                ('data', models.JSONField(help_text='Cached JSON data stored as JSONB in PostgreSQL')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_version', models.CharField(max_length=50)),
                ('record_count', models.IntegerField(default=0)),
                ('file_size_kb', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cached Export',
                'verbose_name_plural': 'Cached Exports',
                'indexes': [models.Index(fields=['export_type'], name='api_cachede_export__ee3d6f_idx'), models.Index(fields=['last_updated'], name='api_cachede_last_up_409fb6_idx')],
            },
        ),
    ]
